//https://seanprashad.com/leetcode-patterns/
using Algorithms;
using Algorithms.tbank_interview;
using Algorithms.tbank_interview.Easy;
using Algorithms.tbank_interview.Medium;
using Algorithms.tbank_interview.Real_T;


//TwoSum.Test();
//NumberOfIslands.Test();
//MergeIntervals.Test();
//ClimbingStairs.Test();
//BestTimetoBuyandSellStock.Test();
//SingleNumber.Test();
//RemoveLinkedListElements.Test();
//ReverseLinkedList.Test();
//ContainsDuplicate.Test();
//MissingNumber.Test();
//MoveZeroes.Test();
//IsSubsequence.Test();
//FindAllNumbersDisappearedinanArray.Test();
//MaximumAverageSubarray.Test();
//FindSmallestLetterGreaterThanTarget.Test();
//BinarSearch.Test();
//BackspaceStringCompare.Test();
//SquaresofaSortedArray.Test();
//ValidAnagram.Test();
//ValidPalindrome.Test();
//ValidParentheses.Test();
//Numberof1Bits.Test();
//ReverseBits.Test();
//AddTwoNumbers.Test();
//LongestSubstringWithoutRepeatingCharacters.Test();
//LongestPalindromicSubstring.Test();
//ContainerWithMostWater.Test();
//MinStackTask.Test();
//RotateImage.Test();
//KeysandRooms.Test();
//FindFirstandLastPositionofElementinSortedArray.Test();
//SimplifyPath.Test();
//FormSmallestNumberFromTwoDigitArrays.Test();
//BattleshipsinBoard.Test();
//LongestSubarrayof1SAfterDeletingOneElement.Test();
//Search2DMatrix.Test();
//MinimumDifferenceBetweenHighestandLowestofKScores.Test();
//CountSquareSubmatriceswithAllOnes.Test();
//SumWithMines.Test();
//MaxHappinessTask.Test();
//WordLadder.Test();
//GroupAnagrams.Test();
//Vacations.Test();
//PermutationinString.Test();
//DecodeString.Test();
SubarraySumsDivisiblebyK.Test();
